
import { Inter } from "next/font/google";
import FooterComponent from "./components/footer/FooterComponent";
import NavbarComponent from "./components/header/navbarPage/NavbarComponent";
import "./globals.css";
import Provider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <Provider>
          <NavbarComponent/>
          
      </Provider>
      {children}
      <FooterComponent/>
    </body>
  </html>
  );
}
